### ISSUE TITLE
needs review

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/sinatra-using-apis#1]
new lab, needs review on master and solution branch 

@AnnJohn @dfenjves 

(sorry, forgot to outline, branch, merge, so someone just needs to read/test out this lab and raise an issue if there is something big that needs to be changed, or just make w/e changes and ping me with the diffs).

**Comment by AnnJohn** [comment]
Assigned to @dfenjves for review

Deadline: 9/17/15
